package models

type InterfaceConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /interface/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configurable items at the global, physical interface
	level
	*/

	//yang_name: type class: leaf
	Type string
	//yang_name: mtu class: leaf
	Mtu uint16
	//yang_name: name class: leaf
	Name string
	//yang_name: description class: leaf
	Description string
	//yang_name: enabled class: leaf
	Enabled bool
}

type InterfaceStateCounters struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /interface/state/counters.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: A collection of interface-related statistics objects.
	*/

	// parent leaf
	Description string
	// parent leaf
	Type string
	// parent leaf
	LastChange uint32
	// parent leaf
	Name string
	// parent leaf
	OperStatus int32
	// parent leaf
	Enabled bool
	// parent leaf
	Mtu uint16
	// parent leaf
	Ifindex uint32
	// parent leaf
	AdminStatus int32
	//yang_name: in-octets class: leaf
	InOctets uint64
	//yang_name: in-unicast-pkts class: leaf
	InUnicastPkts uint64
	//yang_name: in-broadcast-pkts class: leaf
	InBroadcastPkts uint64
	//yang_name: in-multicast-pkts class: leaf
	InMulticastPkts uint64
	//yang_name: in-discards class: leaf
	InDiscards uint64
	//yang_name: in-errors class: leaf
	InErrors uint64
	//yang_name: in-unknown-protos class: leaf
	InUnknownProtos uint32
	//yang_name: out-octets class: leaf
	OutOctets uint64
	//yang_name: out-unicast-pkts class: leaf
	OutUnicastPkts uint64
	//yang_name: out-broadcast-pkts class: leaf
	OutBroadcastPkts uint64
	//yang_name: out-multicast-pkts class: leaf
	OutMulticastPkts uint64
	//yang_name: out-discards class: leaf
	OutDiscards uint64
	//yang_name: out-errors class: leaf
	OutErrors uint64
	//yang_name: last-clear class: leaf
	LastClear string
}

type HoldTimeConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /hold-time/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for interface hold-time settings.
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	// parent leaf
	Type string
	// parent leaf
	Mtu uint16
	//yang_name: up class: leaf
	Up uint32
	//yang_name: down class: leaf
	Down uint32
}

type HoldTimeState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /hold-time/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for interface hold-time.
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	// parent leaf
	Type string
	// parent leaf
	Mtu uint16
	//yang_name: up class: leaf
	Up uint32
	//yang_name: down class: leaf
	Down uint32
}

type SubinterfaceConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configurable items at the subinterface level
	*/

	// parent leaf
	Mtu uint16
	// parent leaf
	Type string
	//yang_name: index class: leaf
	Index uint32
	//yang_name: unnumbered class: leaf
	Unnumbered bool
	//yang_name: name class: leaf
	Name string
	//yang_name: description class: leaf
	Description string
	//yang_name: enabled class: leaf
	Enabled bool
}

type SubinterfaceStateCounters struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/state/counters.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: A collection of interface-related statistics objects.
	*/

	// parent leaf
	Description string
	// parent leaf
	Ifindex uint32
	// parent leaf
	Type string
	// parent leaf
	LastChange uint32
	// parent leaf
	Unnumbered bool
	// parent leaf
	Index uint32
	// parent leaf
	Name string
	// parent leaf
	OperStatus int32
	// parent leaf
	Enabled bool
	// parent leaf
	Mtu uint16
	// parent leaf
	AdminStatus int32
	//yang_name: in-octets class: leaf
	InOctets uint64
	//yang_name: in-unicast-pkts class: leaf
	InUnicastPkts uint64
	//yang_name: in-broadcast-pkts class: leaf
	InBroadcastPkts uint64
	//yang_name: in-multicast-pkts class: leaf
	InMulticastPkts uint64
	//yang_name: in-discards class: leaf
	InDiscards uint64
	//yang_name: in-errors class: leaf
	InErrors uint64
	//yang_name: in-unknown-protos class: leaf
	InUnknownProtos uint32
	//yang_name: out-octets class: leaf
	OutOctets uint64
	//yang_name: out-unicast-pkts class: leaf
	OutUnicastPkts uint64
	//yang_name: out-broadcast-pkts class: leaf
	OutBroadcastPkts uint64
	//yang_name: out-multicast-pkts class: leaf
	OutMulticastPkts uint64
	//yang_name: out-discards class: leaf
	OutDiscards uint64
	//yang_name: out-errors class: leaf
	OutErrors uint64
	//yang_name: last-clear class: leaf
	LastClear string
}

type SubinterfaceVlanConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/vlan/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration parameters for VLANs
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Mtu uint16
	// parent leaf
	Name string
	// parent leaf
	Type string
	// parent leaf
	Unnumbered bool
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: global-vlan-id class: leaf
	GlobalVlanId []uint16
	//yang_name: vlan-id class: leaf-union
	VlanId_VlanId        uint16
	VlanId_VlanId_QinqId string
}

type SubinterfaceVlanState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/vlan/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: State variables for VLANs
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Mtu uint16
	// parent leaf
	Name string
	// parent leaf
	Type string
	// parent leaf
	Unnumbered bool
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: global-vlan-id class: leaf
	GlobalVlanId []uint16
	//yang_name: vlan-id class: leaf-union
	VlanId_VlanId        uint16
	VlanId_VlanId_QinqId string
}

type SubinterfaceIpv4AddressConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv4/address/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for each configured IPv4
	address on the interface
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf
	Unnumbered bool
	// parent leaf
	Enabled bool
	// parent restricted-uint16
	Mtu uint16
	//yang_name: ip class: leaf
	Ip string
	//yang_name: prefix-length class: restricted-uint8
	PrefixLength uint8
}

type SubinterfaceIpv4AddressState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv4/address/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for each IPv4 address
	configured on the interface
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf
	Unnumbered bool
	// parent leaf
	Enabled bool
	// parent restricted-uint16
	Mtu uint16
	//yang_name: ip class: leaf
	Ip string
	//yang_name: prefix-length class: restricted-uint8
	PrefixLength uint8
	//yang_name: origin class: leaf
	Origin int32
}

type SubinterfaceIpv4AddressVrrpVrrpGroupConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv4/address/vrrp/vrrp-group/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for the VRRP group
	*/

	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf
	Description string
	// parent leaf
	Enabled bool
	// parent restricted-uint16
	Mtu uint16
	// parent leaf
	Unnumbered bool
	// parent leaf
	Type string
	// parent leaf
	Name string
	//yang_name: virtual-router-id class: restricted-uint8
	VirtualRouterId uint8
	//yang_name: virtual-address class: leaf-list
	VirtualAddress []string
	//yang_name: priority class: restricted-uint8
	Priority uint8
	//yang_name: preempt class: leaf
	Preempt bool
	//yang_name: preempt-delay class: restricted-uint16
	PreemptDelay uint16
	//yang_name: accept-mode class: leaf
	AcceptMode bool
	//yang_name: advertisement-interval class: restricted-uint16
	AdvertisementInterval uint16
}

type SubinterfaceIpv4AddressVrrpVrrpGroupState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv4/address/vrrp/vrrp-group/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for the VRRP group
	*/

	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	Name string
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent restricted-uint16
	Mtu uint16
	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Unnumbered bool
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: virtual-router-id class: restricted-uint8
	VirtualRouterId uint8
	//yang_name: virtual-address class: leaf-list
	VirtualAddress []string
	//yang_name: priority class: restricted-uint8
	Priority uint8
	//yang_name: preempt class: leaf
	Preempt bool
	//yang_name: preempt-delay class: restricted-uint16
	PreemptDelay uint16
	//yang_name: accept-mode class: leaf
	AcceptMode bool
	//yang_name: advertisement-interval class: restricted-uint16
	AdvertisementInterval uint16
	//yang_name: current-priority class: leaf
	CurrentPriority uint8
}

type SubinterfaceIpv4AddressVrrpVrrpGroupInterfaceTrackingConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv4/address/vrrp/vrrp-group/interface-tracking/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for VRRP interface tracking
	*/

	// parent restricted-uint16
	AdvertisementInterval uint16
	// parent leaf
	AcceptMode bool
	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	Name string
	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf
	VirtualRouterIdKey string `SNAPROUTE: KEY`
	// parent restricted-uint16
	PreemptDelay uint16
	// parent restricted-uint16
	Mtu uint16
	// parent restricted-uint8
	Priority uint8
	// parent leaf
	VirtualAddress []string
	// parent leaf
	Preempt bool
	// parent leaf
	Unnumbered bool
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: track-interface class: leaf
	TrackInterface string
	//yang_name: priority-decrement class: restricted-uint8
	PriorityDecrement uint8
}

type SubinterfaceIpv4AddressVrrpVrrpGroupInterfaceTrackingState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv4/address/vrrp/vrrp-group/interface-tracking/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for VRRP interface tracking
	*/

	// parent restricted-uint16
	AdvertisementInterval uint16
	// parent leaf
	AcceptMode bool
	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	Name string
	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf
	VirtualRouterIdKey string `SNAPROUTE: KEY`
	// parent restricted-uint16
	PreemptDelay uint16
	// parent restricted-uint16
	Mtu uint16
	// parent restricted-uint8
	Priority uint8
	// parent leaf
	VirtualAddress []string
	// parent leaf
	Preempt bool
	// parent leaf
	Unnumbered bool
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: track-interface class: leaf
	TrackInterface string
	//yang_name: priority-decrement class: restricted-uint8
	PriorityDecrement uint8
}

type SubinterfaceIpv4NeighborConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv4/neighbor/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for each configured IPv4
	address on the interface
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf
	Unnumbered bool
	// parent leaf
	Enabled bool
	// parent restricted-uint16
	Mtu uint16
	//yang_name: ip class: leaf
	Ip string
	//yang_name: link-layer-address class: leaf
	LinkLayerAddress string
}

type SubinterfaceIpv4NeighborState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv4/neighbor/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for each IPv4 address
	configured on the interface
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf
	Unnumbered bool
	// parent leaf
	Enabled bool
	// parent restricted-uint16
	Mtu uint16
	//yang_name: ip class: leaf
	Ip string
	//yang_name: link-layer-address class: leaf
	LinkLayerAddress string
	//yang_name: origin class: leaf
	Origin int32
}

type SubinterfaceIpv4Config struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv4/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Top-level IPv4 configuration data for the interface
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf
	Unnumbered bool
	//yang_name: enabled class: leaf
	Enabled bool
	//yang_name: mtu class: restricted-uint16
	Mtu uint16
}

type SubinterfaceIpv4State struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv4/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Top level IPv4 operational state data
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf
	Unnumbered bool
	//yang_name: enabled class: leaf
	Enabled bool
	//yang_name: mtu class: restricted-uint16
	Mtu uint16
}

type SubinterfaceIpv6AddressConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/address/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for each IPv6 address on
	the interface
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf
	Unnumbered bool
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	//yang_name: ip class: leaf
	Ip string
	//yang_name: prefix-length class: restricted-uint8
	PrefixLength uint8
}

type SubinterfaceIpv6AddressState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/address/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: State data for each IPv6 address on the
	interface
	*/

	// parent leaf
	Name string
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	Unnumbered bool
	// parent leaf
	Type string
	// parent leaf
	Description string
	//yang_name: ip class: leaf
	Ip string
	//yang_name: prefix-length class: restricted-uint8
	PrefixLength uint8
	//yang_name: origin class: leaf
	Origin int32
	//yang_name: status class: leaf
	Status int32
}

type SubinterfaceIpv6AddressVrrpVrrpGroupConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/address/vrrp/vrrp-group/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for the VRRP group
	*/

	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	Name string
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	Unnumbered bool
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: virtual-router-id class: restricted-uint8
	VirtualRouterId uint8
	//yang_name: virtual-address class: leaf-list
	VirtualAddress []string
	//yang_name: priority class: restricted-uint8
	Priority uint8
	//yang_name: preempt class: leaf
	Preempt bool
	//yang_name: preempt-delay class: restricted-uint16
	PreemptDelay uint16
	//yang_name: accept-mode class: leaf
	AcceptMode bool
	//yang_name: advertisement-interval class: restricted-uint16
	AdvertisementInterval uint16
	//yang_name: virtual-link-local class: leaf
	VirtualLinkLocal []string
}

type SubinterfaceIpv6AddressVrrpVrrpGroupState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/address/vrrp/vrrp-group/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for the VRRP group
	*/

	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	Name string
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Unnumbered bool
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: virtual-router-id class: restricted-uint8
	VirtualRouterId uint8
	//yang_name: virtual-address class: leaf-list
	VirtualAddress []string
	//yang_name: priority class: restricted-uint8
	Priority uint8
	//yang_name: preempt class: leaf
	Preempt bool
	//yang_name: preempt-delay class: restricted-uint16
	PreemptDelay uint16
	//yang_name: accept-mode class: leaf
	AcceptMode bool
	//yang_name: advertisement-interval class: restricted-uint16
	AdvertisementInterval uint16
	//yang_name: current-priority class: leaf
	CurrentPriority uint8
	//yang_name: virtual-link-local class: leaf
	VirtualLinkLocal []string
}

type SubinterfaceIpv6AddressVrrpVrrpGroupInterfaceTrackingConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/address/vrrp/vrrp-group/interface-tracking/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for VRRP interface tracking
	*/

	// parent restricted-uint16
	AdvertisementInterval uint16
	// parent leaf
	AcceptMode bool
	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	Name string
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf
	VirtualLinkLocal []string
	// parent leaf
	VirtualRouterIdKey string `SNAPROUTE: KEY`
	// parent restricted-uint16
	PreemptDelay uint16
	// parent restricted-uint32
	Mtu uint32
	// parent restricted-uint8
	Priority uint8
	// parent leaf
	VirtualAddress []string
	// parent leaf
	Preempt bool
	// parent leaf
	Unnumbered bool
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: track-interface class: leaf
	TrackInterface string
	//yang_name: priority-decrement class: restricted-uint8
	PriorityDecrement uint8
}

type SubinterfaceIpv6AddressVrrpVrrpGroupInterfaceTrackingState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/address/vrrp/vrrp-group/interface-tracking/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for VRRP interface tracking
	*/

	// parent restricted-uint16
	AdvertisementInterval uint16
	// parent leaf
	AcceptMode bool
	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	Name string
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf
	VirtualLinkLocal []string
	// parent leaf
	VirtualRouterIdKey string `SNAPROUTE: KEY`
	// parent restricted-uint16
	PreemptDelay uint16
	// parent restricted-uint32
	Mtu uint32
	// parent restricted-uint8
	Priority uint8
	// parent leaf
	VirtualAddress []string
	// parent leaf
	Preempt bool
	// parent leaf
	Unnumbered bool
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: track-interface class: leaf
	TrackInterface string
	//yang_name: priority-decrement class: restricted-uint8
	PriorityDecrement uint8
}

type SubinterfaceIpv6NeighborConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/neighbor/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for each IPv6 address on
	the interface
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf
	Unnumbered bool
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	//yang_name: ip class: leaf
	Ip string
	//yang_name: link-layer-address class: leaf
	LinkLayerAddress string
}

type SubinterfaceIpv6NeighborState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/neighbor/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: State data for each IPv6 address on the
	interface
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	Type string
	// parent leaf
	Unnumbered bool
	// parent leaf
	Description string
	//yang_name: ip class: leaf
	Ip string
	//yang_name: link-layer-address class: leaf
	LinkLayerAddress string
	//yang_name: origin class: leaf
	Origin int32
	//yang_name: is-router class: leaf
	IsRouter bool
	//yang_name: neighbor-state class: leaf
	NeighborState int32
}

type SubinterfaceIpv6Config struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Top-level config data for the IPv6 interface
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf
	Unnumbered bool
	//yang_name: enabled class: leaf
	Enabled bool
	//yang_name: mtu class: restricted-uint32
	Mtu uint32
	//yang_name: dup-addr-detect-transmits class: leaf
	DupAddrDetectTransmits uint32
}

type SubinterfaceIpv6State struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Top-level operational state data for the IPv6 interface
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf
	Unnumbered bool
	//yang_name: enabled class: leaf
	Enabled bool
	//yang_name: mtu class: restricted-uint32
	Mtu uint32
	//yang_name: dup-addr-detect-transmits class: leaf
	DupAddrDetectTransmits uint32
}

type SubinterfaceIpv6AutoconfConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/autoconf/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: [adapted from IETF IP model RFC 7277]

	Parameters to control the autoconfiguration of IPv6
	addresses, as described in RFC 4862.
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	Unnumbered bool
	// parent leaf
	Description string
	//yang_name: create-global-addresses class: leaf
	CreateGlobalAddresses bool
	//yang_name: create-temporary-addresses class: leaf
	CreateTemporaryAddresses bool
	//yang_name: temporary-valid-lifetime class: leaf
	TemporaryValidLifetime uint32
	//yang_name: temporary-preferred-lifetime class: leaf
	TemporaryPreferredLifetime uint32
}

type SubinterfaceIpv6AutoconfState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /subinterface/ipv6/autoconf/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data
	*/

	// parent leaf
	IndexKey string `SNAPROUTE: KEY`
	// parent leaf
	Name string
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	Unnumbered bool
	// parent leaf
	Description string
	//yang_name: create-global-addresses class: leaf
	CreateGlobalAddresses bool
	//yang_name: create-temporary-addresses class: leaf
	CreateTemporaryAddresses bool
	//yang_name: temporary-valid-lifetime class: leaf
	TemporaryValidLifetime uint32
	//yang_name: temporary-preferred-lifetime class: leaf
	TemporaryPreferredLifetime uint32
}

type EthernetConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /ethernet/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for ethernet interfaces
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	// parent leaf
	Mtu uint16
	// parent leaf
	Type string
	//yang_name: mac-address class: leaf
	MacAddress string
	//yang_name: duplex-mode class: leaf
	DuplexMode int32
	//yang_name: auto class: leaf
	Auto bool
	//yang_name: speed class: leaf
	Speed string
	//yang_name: enable-flow-control class: leaf
	EnableFlowControl bool
	//yang_name: aggregate-id class: leaf
	AggregateId string
}

type EthernetStateCounters struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /ethernet/state/counters.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Ethernet interface counters
	*/

	// parent leaf
	EnableFlowControl bool
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Enabled bool
	// parent leaf
	DuplexMode int32
	// parent leaf
	AggregateId string
	// parent leaf
	Mtu uint16
	// parent leaf
	Type string
	// parent leaf
	MacAddress string
	// parent leaf
	Description string
	//yang_name: in-mac-control-frames class: leaf
	InMacControlFrames uint64
	//yang_name: in-mac-pause-frames class: leaf
	InMacPauseFrames uint64
	//yang_name: in-oversize-frames class: leaf
	InOversizeFrames uint64
	//yang_name: in-jabber-frames class: leaf
	InJabberFrames uint64
	//yang_name: in-fragment-frames class: leaf
	InFragmentFrames uint64
	//yang_name: in-8021q-frames class: leaf
	In8021qFrames uint64
	//yang_name: in-crc-errors class: leaf
	InCrcErrors uint64
	//yang_name: out-mac-control-frames class: leaf
	OutMacControlFrames uint64
	//yang_name: out-mac-pause-frames class: leaf
	OutMacPauseFrames uint64
	//yang_name: out-8021q-frames class: leaf
	Out8021qFrames uint64
}

type EthernetState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /ethernet/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: State variables for Ethernet interfaces
	*/

	// parent leaf
	EnableFlowControl bool
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	AggregateId string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	// parent leaf
	Mtu uint16
	// parent leaf
	Type string
	// parent leaf
	MacAddress string
	// parent leaf
	DuplexMode int32
	//yang_name: auto class: leaf
	Auto bool
	//yang_name: speed class: leaf
	Speed string
}

type EthernetVlanConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /ethernet/vlan/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration parameters for VLANs
	*/

	// parent leaf
	EnableFlowControl bool
	// parent leaf
	Description string
	// parent leaf
	Enabled bool
	// parent leaf
	DuplexMode int32
	// parent leaf
	AggregateId string
	// parent leaf
	Mtu uint16
	// parent leaf
	Type string
	// parent leaf
	MacAddress string
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	//yang_name: interface-mode class: leaf
	InterfaceMode int32
	//yang_name: native-vlan class: leaf-union
	NativeVlan_VlanId        uint16
	NativeVlan_VlanId_QinqId string
	//yang_name: access-vlan class: leaf-union
	AccessVlan_VlanId        uint16
	AccessVlan_VlanId_QinqId string
	//yang_name: trunk-vlans class: leaf-list
	TrunkVlans_VlanId                              uint16
	TrunkVlans_VlanId_VlanRange                    string
	TrunkVlans_VlanId_VlanRange_QinqId             string
	TrunkVlans_VlanId_VlanRange_QinqId_QinqIdRange string
}

type EthernetVlanState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /ethernet/vlan/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: State variables for VLANs
	*/

	// parent leaf
	EnableFlowControl bool
	// parent leaf
	Description string
	// parent leaf
	Enabled bool
	// parent leaf
	DuplexMode int32
	// parent leaf
	AggregateId string
	// parent leaf
	Mtu uint16
	// parent leaf
	Type string
	// parent leaf
	MacAddress string
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	//yang_name: interface-mode class: leaf
	InterfaceMode int32
	//yang_name: native-vlan class: leaf-union
	NativeVlan_VlanId        uint16
	NativeVlan_VlanId_QinqId string
	//yang_name: access-vlan class: leaf-union
	AccessVlan_VlanId        uint16
	AccessVlan_VlanId_QinqId string
	//yang_name: trunk-vlans class: leaf-list
	TrunkVlans_VlanId                              uint16
	TrunkVlans_VlanId_VlanRange                    string
	TrunkVlans_VlanId_VlanRange_QinqId             string
	TrunkVlans_VlanId_VlanRange_QinqId_QinqIdRange string
}

type AggregationConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /aggregation/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration variables for logical aggregate /
	LAG interfaces
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	// parent leaf
	Type string
	// parent leaf
	Mtu uint16
	//yang_name: lag-type class: leaf
	LagType int32
	//yang_name: min-links class: leaf
	MinLinks uint16
}

type AggregationState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /aggregation/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state variables for logical
	aggregate / LAG interfaces
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	// parent leaf
	Mtu uint16
	// parent leaf
	Type string
	//yang_name: lag-type class: leaf
	LagType int32
	//yang_name: min-links class: leaf
	MinLinks uint16
	//yang_name: members class: leaf-list
	Members []string
}

type AggregationLacpConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /aggregation/lacp/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for LACP
	*/

	// parent leaf
	LagType int32
	// parent leaf
	Description string
	// parent leaf
	Enabled bool
	// parent leaf
	Mtu uint16
	// parent leaf
	MinLinks uint16
	// parent leaf
	Type string
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	//yang_name: interval class: leaf
	Interval int32
	//yang_name: lacp-mode class: leaf
	LacpMode int32
	//yang_name: system-id-mac class: leaf
	SystemIdMac string
	//yang_name: system-priority class: leaf
	SystemPriority uint16
}

type AggregationLacpState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /aggregation/lacp/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for LACP
	*/

	// parent leaf
	LagType int32
	// parent leaf
	Description string
	// parent leaf
	Enabled bool
	// parent leaf
	Mtu uint16
	// parent leaf
	MinLinks uint16
	// parent leaf
	Type string
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	//yang_name: interval class: leaf
	Interval int32
	//yang_name: lacp-mode class: leaf
	LacpMode int32
	//yang_name: system-id-mac class: leaf
	SystemIdMac string
	//yang_name: system-priority class: leaf
	SystemPriority uint16
}

type AggregationLacpMemberStateCounters struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /aggregation/lacp/member/state/counters.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: LACP protocol counters
	*/

	// parent leaf
	Collecting bool
	// parent leaf
	OperKey uint16
	// parent leaf
	PartnerId string
	// parent leaf
	Interface string
	// parent leaf
	Synchronization int32
	// parent leaf
	Aggregatable bool
	// parent leaf
	Mtu uint16
	// parent leaf
	LacpMode int32
	// parent leaf
	PartnerKey uint16
	// parent leaf
	Description string
	// parent leaf
	SystemIdMac string
	// parent leaf
	LagType int32
	// parent leaf
	SystemId string
	// parent leaf
	Interval int32
	// parent leaf
	Enabled bool
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Distributing bool
	// parent leaf
	Timeout int32
	// parent leaf
	Activity int32
	// parent leaf
	SystemPriority uint16
	// parent leaf
	Type string
	// parent leaf
	MinLinks uint16
	//yang_name: lacp-in-pkts class: leaf
	LacpInPkts uint64
	//yang_name: lacp-out-pkts class: leaf
	LacpOutPkts uint64
	//yang_name: lacp-rx-errors class: leaf
	LacpRxErrors uint64
	//yang_name: lacp-tx-errors class: leaf
	LacpTxErrors uint64
	//yang_name: lacp-unknown-errors class: leaf
	LacpUnknownErrors uint64
	//yang_name: lacp-errors class: leaf
	LacpErrors uint64
}

type AggregationVlanConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /aggregation/vlan/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration parameters for VLANs
	*/

	// parent leaf
	LagType int32
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	// parent leaf
	Mtu uint16
	// parent leaf
	Type string
	// parent leaf
	MinLinks uint16
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	//yang_name: interface-mode class: leaf
	InterfaceMode int32
	//yang_name: native-vlan class: leaf-union
	NativeVlan_VlanId        uint16
	NativeVlan_VlanId_QinqId string
	//yang_name: access-vlan class: leaf-union
	AccessVlan_VlanId        uint16
	AccessVlan_VlanId_QinqId string
	//yang_name: trunk-vlans class: leaf-list
	TrunkVlans_VlanId                              uint16
	TrunkVlans_VlanId_VlanRange                    string
	TrunkVlans_VlanId_VlanRange_QinqId             string
	TrunkVlans_VlanId_VlanRange_QinqId_QinqIdRange string
}

type AggregationVlanState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /aggregation/vlan/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: State variables for VLANs
	*/

	// parent leaf
	LagType int32
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	// parent leaf
	Mtu uint16
	// parent leaf
	Type string
	// parent leaf
	MinLinks uint16
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	//yang_name: interface-mode class: leaf
	InterfaceMode int32
	//yang_name: native-vlan class: leaf-union
	NativeVlan_VlanId        uint16
	NativeVlan_VlanId_QinqId string
	//yang_name: access-vlan class: leaf-union
	AccessVlan_VlanId        uint16
	AccessVlan_VlanId_QinqId string
	//yang_name: trunk-vlans class: leaf-list
	TrunkVlans_VlanId                              uint16
	TrunkVlans_VlanId_VlanRange                    string
	TrunkVlans_VlanId_VlanRange_QinqId             string
	TrunkVlans_VlanId_VlanRange_QinqId_QinqIdRange string
}

type RoutedVlanConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for routed vlan interfaces
	*/

	// parent leaf
	Mtu uint16
	// parent leaf
	Description string
	// parent leaf
	Enabled bool
	// parent leaf
	Type string
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	//yang_name: vlan class: leaf-union
	Vlan_Uint16        uint16
	Vlan_Uint16_String string
}

type RoutedVlanState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data
	*/

	// parent leaf
	Mtu uint16
	// parent leaf
	Description string
	// parent leaf
	Enabled bool
	// parent leaf
	Type string
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	//yang_name: vlan class: leaf-union
	Vlan_Uint16        uint16
	Vlan_Uint16_String string
}

type RoutedVlanIpv4AddressConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv4/address/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for each configured IPv4
	address on the interface
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Enabled bool
	// parent restricted-uint16
	Mtu uint16
	//yang_name: ip class: leaf
	Ip string
	//yang_name: prefix-length class: restricted-uint8
	PrefixLength uint8
}

type RoutedVlanIpv4AddressState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv4/address/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for each IPv4 address
	configured on the interface
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Enabled bool
	// parent restricted-uint16
	Mtu uint16
	//yang_name: ip class: leaf
	Ip string
	//yang_name: prefix-length class: restricted-uint8
	PrefixLength uint8
	//yang_name: origin class: leaf
	Origin int32
}

type RoutedVlanIpv4AddressVrrpVrrpGroupConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv4/address/vrrp/vrrp-group/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for the VRRP group
	*/

	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf
	Description string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Enabled bool
	// parent restricted-uint16
	Mtu uint16
	// parent leaf
	Type string
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	//yang_name: virtual-router-id class: restricted-uint8
	VirtualRouterId uint8
	//yang_name: virtual-address class: leaf-list
	VirtualAddress []string
	//yang_name: priority class: restricted-uint8
	Priority uint8
	//yang_name: preempt class: leaf
	Preempt bool
	//yang_name: preempt-delay class: restricted-uint16
	PreemptDelay uint16
	//yang_name: accept-mode class: leaf
	AcceptMode bool
	//yang_name: advertisement-interval class: restricted-uint16
	AdvertisementInterval uint16
}

type RoutedVlanIpv4AddressVrrpVrrpGroupState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv4/address/vrrp/vrrp-group/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for the VRRP group
	*/

	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent restricted-uint16
	Mtu uint16
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: virtual-router-id class: restricted-uint8
	VirtualRouterId uint8
	//yang_name: virtual-address class: leaf-list
	VirtualAddress []string
	//yang_name: priority class: restricted-uint8
	Priority uint8
	//yang_name: preempt class: leaf
	Preempt bool
	//yang_name: preempt-delay class: restricted-uint16
	PreemptDelay uint16
	//yang_name: accept-mode class: leaf
	AcceptMode bool
	//yang_name: advertisement-interval class: restricted-uint16
	AdvertisementInterval uint16
	//yang_name: current-priority class: leaf
	CurrentPriority uint8
}

type RoutedVlanIpv4AddressVrrpVrrpGroupInterfaceTrackingConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv4/address/vrrp/vrrp-group/interface-tracking/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for VRRP interface tracking
	*/

	// parent restricted-uint16
	AdvertisementInterval uint16
	// parent leaf
	AcceptMode bool
	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	VirtualRouterIdKey string `SNAPROUTE: KEY`
	// parent restricted-uint16
	PreemptDelay uint16
	// parent restricted-uint16
	Mtu uint16
	// parent restricted-uint8
	Priority uint8
	// parent leaf
	VirtualAddress []string
	// parent leaf
	Preempt bool
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: track-interface class: leaf
	TrackInterface string
	//yang_name: priority-decrement class: restricted-uint8
	PriorityDecrement uint8
}

type RoutedVlanIpv4AddressVrrpVrrpGroupInterfaceTrackingState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv4/address/vrrp/vrrp-group/interface-tracking/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for VRRP interface tracking
	*/

	// parent restricted-uint16
	AdvertisementInterval uint16
	// parent leaf
	AcceptMode bool
	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	VirtualRouterIdKey string `SNAPROUTE: KEY`
	// parent restricted-uint16
	PreemptDelay uint16
	// parent restricted-uint16
	Mtu uint16
	// parent restricted-uint8
	Priority uint8
	// parent leaf
	VirtualAddress []string
	// parent leaf
	Preempt bool
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: track-interface class: leaf
	TrackInterface string
	//yang_name: priority-decrement class: restricted-uint8
	PriorityDecrement uint8
}

type RoutedVlanIpv4NeighborConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv4/neighbor/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for each configured IPv4
	address on the interface
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Enabled bool
	// parent restricted-uint16
	Mtu uint16
	//yang_name: ip class: leaf
	Ip string
	//yang_name: link-layer-address class: leaf
	LinkLayerAddress string
}

type RoutedVlanIpv4NeighborState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv4/neighbor/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for each IPv4 address
	configured on the interface
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Enabled bool
	// parent restricted-uint16
	Mtu uint16
	//yang_name: ip class: leaf
	Ip string
	//yang_name: link-layer-address class: leaf
	LinkLayerAddress string
	//yang_name: origin class: leaf
	Origin int32
}

type RoutedVlanIpv4Config struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv4/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Top-level IPv4 configuration data for the interface
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Description string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Type string
	//yang_name: enabled class: leaf
	Enabled bool
	//yang_name: mtu class: restricted-uint16
	Mtu uint16
}

type RoutedVlanIpv4State struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv4/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Top level IPv4 operational state data
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Description string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Type string
	//yang_name: enabled class: leaf
	Enabled bool
	//yang_name: mtu class: restricted-uint16
	Mtu uint16
}

type RoutedVlanIpv6AddressConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/address/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for each IPv6 address on
	the interface
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	//yang_name: ip class: leaf
	Ip string
	//yang_name: prefix-length class: restricted-uint8
	PrefixLength uint8
}

type RoutedVlanIpv6AddressState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/address/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: State data for each IPv6 address on the
	interface
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	Type string
	// parent leaf
	Description string
	//yang_name: ip class: leaf
	Ip string
	//yang_name: prefix-length class: restricted-uint8
	PrefixLength uint8
	//yang_name: origin class: leaf
	Origin int32
	//yang_name: status class: leaf
	Status int32
}

type RoutedVlanIpv6AddressVrrpVrrpGroupConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/address/vrrp/vrrp-group/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for the VRRP group
	*/

	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: virtual-router-id class: restricted-uint8
	VirtualRouterId uint8
	//yang_name: virtual-address class: leaf-list
	VirtualAddress []string
	//yang_name: priority class: restricted-uint8
	Priority uint8
	//yang_name: preempt class: leaf
	Preempt bool
	//yang_name: preempt-delay class: restricted-uint16
	PreemptDelay uint16
	//yang_name: accept-mode class: leaf
	AcceptMode bool
	//yang_name: advertisement-interval class: restricted-uint16
	AdvertisementInterval uint16
	//yang_name: virtual-link-local class: leaf
	VirtualLinkLocal []string
}

type RoutedVlanIpv6AddressVrrpVrrpGroupState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/address/vrrp/vrrp-group/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for the VRRP group
	*/

	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: virtual-router-id class: restricted-uint8
	VirtualRouterId uint8
	//yang_name: virtual-address class: leaf-list
	VirtualAddress []string
	//yang_name: priority class: restricted-uint8
	Priority uint8
	//yang_name: preempt class: leaf
	Preempt bool
	//yang_name: preempt-delay class: restricted-uint16
	PreemptDelay uint16
	//yang_name: accept-mode class: leaf
	AcceptMode bool
	//yang_name: advertisement-interval class: restricted-uint16
	AdvertisementInterval uint16
	//yang_name: current-priority class: leaf
	CurrentPriority uint8
	//yang_name: virtual-link-local class: leaf
	VirtualLinkLocal []string
}

type RoutedVlanIpv6AddressVrrpVrrpGroupInterfaceTrackingConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/address/vrrp/vrrp-group/interface-tracking/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for VRRP interface tracking
	*/

	// parent restricted-uint16
	AdvertisementInterval uint16
	// parent leaf
	AcceptMode bool
	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf
	VirtualLinkLocal []string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	VirtualRouterIdKey string `SNAPROUTE: KEY`
	// parent restricted-uint16
	PreemptDelay uint16
	// parent restricted-uint32
	Mtu uint32
	// parent restricted-uint8
	Priority uint8
	// parent leaf
	VirtualAddress []string
	// parent leaf
	Preempt bool
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: track-interface class: leaf
	TrackInterface string
	//yang_name: priority-decrement class: restricted-uint8
	PriorityDecrement uint8
}

type RoutedVlanIpv6AddressVrrpVrrpGroupInterfaceTrackingState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/address/vrrp/vrrp-group/interface-tracking/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data for VRRP interface tracking
	*/

	// parent restricted-uint16
	AdvertisementInterval uint16
	// parent leaf
	AcceptMode bool
	// parent restricted-uint8
	PrefixLength uint8
	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	IpKey string `SNAPROUTE: KEY`
	// parent leaf
	VirtualLinkLocal []string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	VirtualRouterIdKey string `SNAPROUTE: KEY`
	// parent restricted-uint16
	PreemptDelay uint16
	// parent restricted-uint32
	Mtu uint32
	// parent restricted-uint8
	Priority uint8
	// parent leaf
	VirtualAddress []string
	// parent leaf
	Preempt bool
	// parent leaf
	Type string
	// parent leaf
	Enabled bool
	// parent leaf
	Description string
	//yang_name: track-interface class: leaf
	TrackInterface string
	//yang_name: priority-decrement class: restricted-uint8
	PriorityDecrement uint8
}

type RoutedVlanIpv6NeighborConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/neighbor/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Configuration data for each IPv6 address on
	the interface
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	//yang_name: ip class: leaf
	Ip string
	//yang_name: link-layer-address class: leaf
	LinkLayerAddress string
}

type RoutedVlanIpv6NeighborState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/neighbor/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: State data for each IPv6 address on the
	interface
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	Type string
	// parent leaf
	Description string
	//yang_name: ip class: leaf
	Ip string
	//yang_name: link-layer-address class: leaf
	LinkLayerAddress string
	//yang_name: origin class: leaf
	Origin int32
	//yang_name: is-router class: leaf
	IsRouter bool
	//yang_name: neighbor-state class: leaf
	NeighborState int32
}

type RoutedVlanIpv6Config struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Top-level config data for the IPv6 interface
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	//yang_name: enabled class: leaf
	Enabled bool
	//yang_name: mtu class: restricted-uint32
	Mtu uint32
	//yang_name: dup-addr-detect-transmits class: leaf
	DupAddrDetectTransmits uint32
}

type RoutedVlanIpv6State struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Top-level operational state data for the IPv6 interface
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	Type string
	// parent leaf
	Description string
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	//yang_name: enabled class: leaf
	Enabled bool
	//yang_name: mtu class: restricted-uint32
	Mtu uint32
	//yang_name: dup-addr-detect-transmits class: leaf
	DupAddrDetectTransmits uint32
}

type RoutedVlanIpv6AutoconfConfig struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/autoconf/config.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: [adapted from IETF IP model RFC 7277]

	Parameters to control the autoconfiguration of IPv6
	addresses, as described in RFC 4862.
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	Type string
	// parent leaf
	Description string
	//yang_name: create-global-addresses class: leaf
	CreateGlobalAddresses bool
	//yang_name: create-temporary-addresses class: leaf
	CreateTemporaryAddresses bool
	//yang_name: temporary-valid-lifetime class: leaf
	TemporaryValidLifetime uint32
	//yang_name: temporary-preferred-lifetime class: leaf
	TemporaryPreferredLifetime uint32
}

type RoutedVlanIpv6AutoconfState struct {
	/*
	    This class was auto-generated by the GOSTRUCT plugin for PYANG
	    from YANG module openconfig-interfaces
	    based on the path /routed-vlan/ipv6/autoconf/state.
	    Each member element of the container is represented as a struct
	    variable - with a specific YANG type.

		YANG Description: Operational state data
	*/

	// parent leaf
	NameKey string `SNAPROUTE: KEY`
	// parent leaf
	DupAddrDetectTransmits uint32
	// parent leaf-union
	vlan_Uint16 uint16
	vlan_String string
	// parent leaf
	Enabled bool
	// parent restricted-uint32
	Mtu uint32
	// parent leaf
	Type string
	// parent leaf
	Description string
	//yang_name: create-global-addresses class: leaf
	CreateGlobalAddresses bool
	//yang_name: create-temporary-addresses class: leaf
	CreateTemporaryAddresses bool
	//yang_name: temporary-valid-lifetime class: leaf
	TemporaryValidLifetime uint32
	//yang_name: temporary-preferred-lifetime class: leaf
	TemporaryPreferredLifetime uint32
}
