package models

import (
	"encoding/json"
	"fmt"
)

//
// This file is handcoded for now. Eventually this would be generated by yang compiler
//
type IPV4AddressBlock struct {
	BaseObj
	NwAddress         string `SNAPROUTE: "KEY"`
	NetworkMask       string `SNAPROUTE: "KEY"`
	HostIntfIp        string
}

func (obj IPV4AddressBlock ) UnmarshalObject(body []byte) (ConfigObj, error) {
	var v4block IPV4AddressBlock
	var err error
	if len(body) > 0 {
		if err = json.Unmarshal(body, &v4block); err != nil {
			fmt.Printf("### Trouble in unmarshaling IPV4Block from Json Error: %s", err)
		}
	}
	return v4block, err
}

