package models

//
// This file is handcoded for now. Eventually this would be generated by yang compiler
//
var ConfigObjectMap = map[string] ConfigObj{ "V4Route"      : &IPV4Route{},
                                             "Vlan"         : &Vlan{},
                                             "IPv4Intf"     : &IPv4Intf{},
                                             "IPv4Neighbor" : &IPv4Neighbor{}}
