package models

type Dot1dStpPortEntryConfig struct {
	/*
		    This class was auto-generated by the GOSTRUCT plugin for PYANG
		    from YANG module BRIDGE-MIB
		    based on the path /dot1dStpPortEntry/Config.
		    Each member element of the container is represented as a struct
		    variable - with a specific YANG type.

			YANG Description: configuration data related to stp port
	*/

	BaseObj
	// parent restricted-int32
	Dot1dStpPortKey int32 `SNAPROUTE: KEY`
	//yang_name: dot1dStpPortPriority class: restricted-int32
	Dot1dStpPortPriority int32
	//yang_name: dot1dStpPortEnable class: leaf
	Dot1dStpPortEnable int32
	//yang_name: dot1dStpPortPathCost class: restricted-int32
	Dot1dStpPortPathCost int32
	//yang_name: dot1dStpPortPathCost32 class: restricted-int32
	Dot1dStpPortPathCost32 int32
	//yang_name: dot1dStpPortProtocolMigration class: leaf
	Dot1dStpPortProtocolMigration int32
	//yang_name: dot1dStpPortAdminPointToPoint class: leaf
	Dot1dStpPortAdminPointToPoint int32
	//yang_name: dot1dStpPortAdminEdgePort class: leaf
	Dot1dStpPortAdminEdgePort int32
	//yang_name: dot1dStpPortAdminPathCost class: restricted-int32
	Dot1dStpPortAdminPathCost int32
}

type Dot1dStpPortEntryState struct {
	/*
		    This class was auto-generated by the GOSTRUCT plugin for PYANG
		    from YANG module BRIDGE-MIB
		    based on the path /dot1dStpPortEntry/State.
		    Each member element of the container is represented as a struct
		    variable - with a specific YANG type.

			YANG Description: status data related to stp port
	*/

	BaseObj
	// parent restricted-int32
	Dot1dStpPortPathCost32 int32
	// parent restricted-int32
	Dot1dStpPortPriority int32
	// parent leaf
	Dot1dStpPortAdminPointToPoint int32
	// parent leaf
	Dot1dStpPortProtocolMigration int32
	// parent restricted-int32
	Dot1dStpPortKey int32 `SNAPROUTE: KEY`
	// parent leaf
	Dot1dStpPortAdminEdgePort int32
	// parent restricted-int32
	Dot1dStpPortPathCost int32
	// parent restricted-int32
	Dot1dStpPortAdminPathCost int32
	// parent leaf
	Dot1dStpPortEnable int32
	//yang_name: dot1dStpPortState class: leaf
	Dot1dStpPortState int32
	//yang_name: dot1dStpPortDesignatedRoot class: leaf
	Dot1dStpPortDesignatedRoot string
	//yang_name: dot1dStpPortDesignatedCost class: leaf
	Dot1dStpPortDesignatedCost int32
	//yang_name: dot1dStpPortDesignatedBridge class: leaf
	Dot1dStpPortDesignatedBridge string
	//yang_name: dot1dStpPortDesignatedPort class: restricted-binary
	Dot1dStpPortDesignatedPort string
	//yang_name: dot1dStpPortForwardTransitions class: leaf
	Dot1dStpPortForwardTransitions uint32
	//yang_name: dot1dStpPortOperEdgePort class: leaf
	Dot1dStpPortOperEdgePort int32
	//yang_name: dot1dStpPortOperPointToPoint class: leaf
	Dot1dStpPortOperPointToPoint int32
}

type Dot1dStpBridgeConfig struct {
	/*
	   This class was auto-generated by the GOSTRUCT plugin for PYANG
	   from YANG module BRIDGE-MIB
	   based on the path /dot1dStpBridge/Config.
	   Each member element of the container is represented as a struct
	   variable - with a specific YANG type.
	*/

	BaseObj
	// parent leaf
	Dot1dBridgeAddressKey string `SNAPROUTE: KEY`
	// parent restricted-int32
	Dot1dStpPriorityKey int32 `SNAPROUTE: KEY`
	//yang_name: dot1dStpBridgeMaxAge class: restricted-int32
	Dot1dStpBridgeMaxAge int32
	//yang_name: dot1dStpBridgeHelloTime class: restricted-int32
	Dot1dStpBridgeHelloTime int32
	//yang_name: dot1dStpBridgeForwardDelay class: restricted-int32
	Dot1dStpBridgeForwardDelay int32
}

type Dot1dStpBridgeState struct {
	/*
	   This class was auto-generated by the GOSTRUCT plugin for PYANG
	   from YANG module BRIDGE-MIB
	   based on the path /dot1dStpBridge/State.
	   Each member element of the container is represented as a struct
	   variable - with a specific YANG type.
	*/

	BaseObj
	// parent leaf
	Dot1dBridgeAddressKey string `SNAPROUTE: KEY`
	// parent restricted-int32
	Dot1dStpBridgeHelloTime int32
	// parent restricted-int32
	Dot1dStpBridgeForwardDelay int32
	// parent restricted-int32
	Dot1dStpBridgeMaxAge int32
	// parent restricted-int32
	Dot1dStpPriorityKey int32 `SNAPROUTE: KEY`
	//yang_name: dot1dStpProtocolSpecification class: leaf
	Dot1dStpProtocolSpecification int32
	//yang_name: dot1dStpTimeSinceTopologyChange class: leaf
	Dot1dStpTimeSinceTopologyChange uint32
	//yang_name: dot1dStpTopChanges class: leaf
	Dot1dStpTopChanges uint32
	//yang_name: dot1dStpDesignatedRoot class: leaf
	Dot1dStpDesignatedRoot string
	//yang_name: dot1dStpRootCost class: leaf
	Dot1dStpRootCost int32
	//yang_name: dot1dStpRootPort class: leaf
	Dot1dStpRootPort int32
	//yang_name: dot1dStpMaxAge class: leaf
	Dot1dStpMaxAge int32
	//yang_name: dot1dStpHelloTime class: leaf
	Dot1dStpHelloTime int32
	//yang_name: dot1dStpHoldTime class: leaf
	Dot1dStpHoldTime int32
	//yang_name: dot1dStpForwardDelay class: leaf
	Dot1dStpForwardDelay int32
}
